# Generated by Django 4.2.3 on 2023-09-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='mark',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
